ARG STAGE="dig"
ARG ECR_URL="registry.digitalocean.com/etherealengine"
ARG REPO_NAME="etherealengine"

FROM ${ECR_URL}/${REPO_NAME}-dig-root:latest_${STAGE} as builder

COPY . .

CMD ["scripts/strip-engine.sh"]

CMD ["scripts/setup_helm.sh"]

# copy then compile the code

ENV APP_ENV=production

FROM node:18-buster-slim as runner
WORKDIR /app

COPY --from=builder /app ./

CMD ["scripts/run-builder.sh"]
