FROM microk8s.registry:32000/ee-base1:latest as builder

COPY . .

CMD ["scripts/strip-engine.sh"]

CMD ["scripts/setup_helm.sh"]

# copy then compile the code

ENV APP_ENV=production

FROM node:18-buster-slim as runner
WORKDIR /app

COPY --from=builder /app ./

CMD ["scripts/run-builder.sh"]
